# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(889, 490)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 865, 373))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setContentsMargins(10, 10, 10, 10)
        self.formLayout_3.setObjectName("formLayout_3")
        self.fRAC1Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.fRAC1Label.setObjectName("fRAC1Label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.fRAC1Label)
        self.fRAC1LineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.fRAC1LineEdit.setObjectName("fRAC1LineEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fRAC1LineEdit)
        self.fRAC2Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.fRAC2Label.setObjectName("fRAC2Label")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.fRAC2Label)
        self.fRAC2LineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.fRAC2LineEdit.setObjectName("fRAC2LineEdit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fRAC2LineEdit)
        self.fRAC3Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.fRAC3Label.setObjectName("fRAC3Label")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.fRAC3Label)
        self.fRAC3LineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.fRAC3LineEdit.setObjectName("fRAC3LineEdit")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fRAC3LineEdit)
        self.fRAC4Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.fRAC4Label.setObjectName("fRAC4Label")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.fRAC4Label)
        self.fRAC4LineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.fRAC4LineEdit.setObjectName("fRAC4LineEdit")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.fRAC4LineEdit)
        self.fRAC5Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.fRAC5Label.setObjectName("fRAC5Label")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.fRAC5Label)
        self.fRAC5LineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.fRAC5LineEdit.setObjectName("fRAC5LineEdit")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.fRAC5LineEdit)
        self.fRAC6Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.fRAC6Label.setObjectName("fRAC6Label")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.fRAC6Label)
        self.fRAC6LineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.fRAC6LineEdit.setObjectName("fRAC6LineEdit")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.fRAC6LineEdit)
        self.tEMPLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.tEMPLabel.setObjectName("tEMPLabel")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.tEMPLabel)
        self.tEMPLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.tEMPLineEdit.setObjectName("tEMPLineEdit")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.tEMPLineEdit)
        self.tORRLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.tORRLabel.setObjectName("tORRLabel")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.tORRLabel)
        self.tORRLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.tORRLineEdit.setObjectName("tORRLineEdit")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.tORRLineEdit)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.gridLayout.addLayout(self.formLayout_3, 0, 2, 1, 1)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setContentsMargins(10, 10, 10, 10)
        self.formLayout_4.setObjectName("formLayout_4")
        self.eFIELDLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.eFIELDLabel.setObjectName("eFIELDLabel")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.eFIELDLabel)
        self.eFIELDLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.eFIELDLineEdit.setObjectName("eFIELDLineEdit")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.eFIELDLineEdit)
        self.bMAGLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.bMAGLabel.setObjectName("bMAGLabel")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.bMAGLabel)
        self.bMAGLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.bMAGLineEdit.setObjectName("bMAGLineEdit")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bMAGLineEdit)
        self.bTHETALabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.bTHETALabel.setObjectName("bTHETALabel")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.bTHETALabel)
        self.bTHETALineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.bTHETALineEdit.setObjectName("bTHETALineEdit")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bTHETALineEdit)
        self.iWRITELabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.iWRITELabel.setObjectName("iWRITELabel")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.iWRITELabel)
        self.iWRITELineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.iWRITELineEdit.setObjectName("iWRITELineEdit")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.iWRITELineEdit)
        self.iPENLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.iPENLabel.setObjectName("iPENLabel")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.iPENLabel)
        self.iPENLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.iPENLineEdit.setObjectName("iPENLineEdit")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.iPENLineEdit)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_4)
        self.gridLayout.addLayout(self.formLayout_4, 0, 3, 1, 1)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setContentsMargins(10, 10, 10, 10)
        self.formLayout_5.setObjectName("formLayout_5")
        self.dETEFFLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.dETEFFLabel.setObjectName("dETEFFLabel")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dETEFFLabel)
        self.dETEFFLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.dETEFFLineEdit.setObjectName("dETEFFLineEdit")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dETEFFLineEdit)
        self.eXCWGHTLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.eXCWGHTLabel.setObjectName("eXCWGHTLabel")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.eXCWGHTLabel)
        self.eXCWGHTLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.eXCWGHTLineEdit.setObjectName("eXCWGHTLineEdit")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.eXCWGHTLineEdit)
        self.kGASLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.kGASLabel.setObjectName("kGASLabel")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.kGASLabel)
        self.kGASLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.kGASLineEdit.setObjectName("kGASLineEdit")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.kGASLineEdit)
        self.lGASLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lGASLabel.setObjectName("lGASLabel")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lGASLabel)
        self.lGASLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lGASLineEdit.setObjectName("lGASLineEdit")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lGASLineEdit)
        self.lCMPLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lCMPLabel.setObjectName("lCMPLabel")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lCMPLabel)
        self.lCMPLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lCMPLineEdit.setObjectName("lCMPLineEdit")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lCMPLineEdit)
        self.lRAYLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lRAYLabel.setObjectName("lRAYLabel")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lRAYLabel)
        self.lRAYLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lRAYLineEdit.setObjectName("lRAYLineEdit")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lRAYLineEdit)
        self.lPAPLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lPAPLabel.setObjectName("lPAPLabel")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lPAPLabel)
        self.lPAPLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lPAPLineEdit.setObjectName("lPAPLineEdit")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lPAPLineEdit)
        self.lBRMLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lBRMLabel.setObjectName("lBRMLabel")
        self.formLayout_5.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lBRMLabel)
        self.lBRMLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lBRMLineEdit.setObjectName("lBRMLineEdit")
        self.formLayout_5.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lBRMLineEdit)
        self.iECASCLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.iECASCLabel.setObjectName("iECASCLabel")
        self.formLayout_5.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.iECASCLabel)
        self.iECASCLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.iECASCLineEdit.setObjectName("iECASCLineEdit")
        self.formLayout_5.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.iECASCLineEdit)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_5)
        self.gridLayout.addLayout(self.formLayout_5, 0, 4, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(10, 10, 10, 10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.nGAS1Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.nGAS1Label.setObjectName("nGAS1Label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.nGAS1Label)
        self.nGAS1LineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.nGAS1LineEdit.setObjectName("nGAS1LineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nGAS1LineEdit)
        self.nGAS2Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.nGAS2Label.setObjectName("nGAS2Label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.nGAS2Label)
        self.nGAS2LineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.nGAS2LineEdit.setObjectName("nGAS2LineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nGAS2LineEdit)
        self.nGAS3Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.nGAS3Label.setObjectName("nGAS3Label")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.nGAS3Label)
        self.nGAS3LineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.nGAS3LineEdit.setObjectName("nGAS3LineEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.nGAS3LineEdit)
        self.nGAS4Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.nGAS4Label.setObjectName("nGAS4Label")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.nGAS4Label)
        self.nGAS4LineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.nGAS4LineEdit.setObjectName("nGAS4LineEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.nGAS4LineEdit)
        self.nGAS5Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.nGAS5Label.setObjectName("nGAS5Label")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.nGAS5Label)
        self.nGAS5LineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.nGAS5LineEdit.setObjectName("nGAS5LineEdit")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.nGAS5LineEdit)
        self.nGAS6Label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.nGAS6Label.setObjectName("nGAS6Label")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.nGAS6Label)
        self.nGAS6LineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.nGAS6LineEdit.setObjectName("nGAS6LineEdit")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.nGAS6LineEdit)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.gridLayout.addLayout(self.formLayout_2, 0, 1, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        self.nGASLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.nGASLabel.setObjectName("nGASLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.nGASLabel)
        self.nGASLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.nGASLineEdit.setObjectName("nGASLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nGASLineEdit)
        self.nDELTALabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.nDELTALabel.setObjectName("nDELTALabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.nDELTALabel)
        self.nDELTALineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.nDELTALineEdit.setObjectName("nDELTALineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nDELTALineEdit)
        self.iMIPLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.iMIPLabel.setObjectName("iMIPLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.iMIPLabel)
        self.iMIPLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.iMIPLineEdit.setObjectName("iMIPLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.iMIPLineEdit)
        self.nDVECLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.nDVECLabel.setObjectName("nDVECLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.nDVECLabel)
        self.nDVECLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.nDVECLineEdit.setObjectName("nDVECLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.nDVECLineEdit)
        self.nSEEDLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.nSEEDLabel.setObjectName("nSEEDLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.nSEEDLabel)
        self.nSEEDLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.nSEEDLineEdit.setObjectName("nSEEDLineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.nSEEDLineEdit)
        self.eSTARTLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.eSTARTLabel.setObjectName("eSTARTLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.eSTARTLabel)
        self.eSTARTLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.eSTARTLineEdit.setObjectName("eSTARTLineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.eSTARTLineEdit)
        self.eTHRMLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.eTHRMLabel.setObjectName("eTHRMLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.eTHRMLabel)
        self.eTHRMLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.eTHRMLineEdit.setObjectName("eTHRMLineEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.eTHRMLineEdit)
        self.eCUTLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.eCUTLabel.setObjectName("eCUTLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.eCUTLabel)
        self.eCUTLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.eCUTLineEdit.setObjectName("eCUTLineEdit")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.eCUTLineEdit)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 889, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fRAC1Label.setText(_translate("MainWindow", "FRAC1"))
        self.fRAC2Label.setText(_translate("MainWindow", "FRAC2"))
        self.fRAC3Label.setText(_translate("MainWindow", "FRAC3"))
        self.fRAC4Label.setText(_translate("MainWindow", "FRAC4"))
        self.fRAC5Label.setText(_translate("MainWindow", "FRAC5"))
        self.fRAC6Label.setText(_translate("MainWindow", "FRAC6"))
        self.tEMPLabel.setText(_translate("MainWindow", "TEMP"))
        self.tORRLabel.setText(_translate("MainWindow", "TORR"))
        self.label_3.setText(_translate("MainWindow", "Card 3"))
        self.eFIELDLabel.setText(_translate("MainWindow", "EFIELD"))
        self.bMAGLabel.setText(_translate("MainWindow", "BMAG"))
        self.bTHETALabel.setText(_translate("MainWindow", "BTHETA"))
        self.iWRITELabel.setText(_translate("MainWindow", "IWRITE"))
        self.iPENLabel.setText(_translate("MainWindow", "IPEN"))
        self.label_4.setText(_translate("MainWindow", "Card 4"))
        self.dETEFFLabel.setText(_translate("MainWindow", "DETEFF"))
        self.eXCWGHTLabel.setText(_translate("MainWindow", "EXCWGHT"))
        self.kGASLabel.setText(_translate("MainWindow", "KGAS"))
        self.lGASLabel.setText(_translate("MainWindow", "LGAS"))
        self.lCMPLabel.setText(_translate("MainWindow", "LCMP"))
        self.lRAYLabel.setText(_translate("MainWindow", "LRAY"))
        self.lPAPLabel.setText(_translate("MainWindow", "LPAP"))
        self.lBRMLabel.setText(_translate("MainWindow", "LBRM"))
        self.iECASCLabel.setText(_translate("MainWindow", "IECASC"))
        self.label_5.setText(_translate("MainWindow", "Card 5"))
        self.nGAS1Label.setText(_translate("MainWindow", "NGAS1"))
        self.nGAS2Label.setText(_translate("MainWindow", "NGAS2"))
        self.nGAS3Label.setText(_translate("MainWindow", "NGAS3"))
        self.nGAS4Label.setText(_translate("MainWindow", "NGAS4"))
        self.nGAS5Label.setText(_translate("MainWindow", "NGAS5"))
        self.nGAS6Label.setText(_translate("MainWindow", "NGAS6"))
        self.label_2.setText(_translate("MainWindow", "Card 2"))
        self.label.setText(_translate("MainWindow", "Card 1"))
        self.nGASLabel.setText(_translate("MainWindow", "NGAS"))
        self.nDELTALabel.setText(_translate("MainWindow", "NDELTA"))
        self.iMIPLabel.setText(_translate("MainWindow", "IMIP"))
        self.nDVECLabel.setText(_translate("MainWindow", "NDVEC"))
        self.nSEEDLabel.setText(_translate("MainWindow", "NSEED"))
        self.eSTARTLabel.setText(_translate("MainWindow", "ESTART"))
        self.eTHRMLabel.setText(_translate("MainWindow", "ETHRM"))
        self.eCUTLabel.setText(_translate("MainWindow", "ECUT"))
        self.pushButton_2.setText(_translate("MainWindow", "Reset"))
        self.pushButton_3.setText(_translate("MainWindow", "Quit"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))

